### ISSUE TITLE
add PDF versions of docs, slide decks, etc

### ISSUE THREAD

**Issue by tofr** [hunter-teacher-cert/summer-2020-topics-project-aisearchjacksam#3]
...b/c googdoc links are transient, goog is known for changing things w/o warning, docs may accidentally disappear, etc.  And MS Office not reliably openable on everyone's machines.
PDF version will help guarantee this repo of greater use to anyone from the cohort who utilizes this repo in the future... PDF is cross-platfrom, reliable, viewable right here in github...

**Comment by JackRMccoy** [comment]
All set.  Thanks again for all the support, Topher!  I hope you have a safe and enjoyable August!
